### ISSUE TITLE
Vegas fails to work when `circe 0.9.3` is imported in Zeppelin 

### ISSUE THREAD

**Issue by dankolesnikov** [vegas-viz/Vegas#156]
Vegas doesn't graph if the user imports circe 0.9.3 in Zeppelin. 

To reproduce in Zeppelin, import the following in the spark interpreter and run a sample Vegas example: 
* org.vegas-viz:vegas_2.11:0.3.11
* io.circe:circe-core_2.11:0.9.3

Throws exception: 
```
java.lang.NoSuchMethodError: io.circe.Printer.copy(ZZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lio/circe/Printer;
  at vegas.spec.package$.<init>(package.scala:11)
  at vegas.spec.package$.<clinit>(package.scala)
  at vegas.DSL.ExtendedUnitSpecBuilder.toJson(SpecDSL.scala:55)
  at vegas.render.ShowHTML.apply(ShowRender.scala:19)
  at vegas.render.ShowHTML.apply(ShowRender.scala:18)
  at vegas.DSL.SpecBuilder$SpecBuilderRenderOps$.show$extension(SpecDSL.scala:99)
```
Attaching screenshots:
Failure: circe 0.9.3 is imported
![vegaszeppelinfailure](https://user-images.githubusercontent.com/10562358/45579681-99a4d600-b83e-11e8-8e1e-6513bac0b960.png)

Success: no circe library is imported
![vegaszeppelinsuccess](https://user-images.githubusercontent.com/10562358/45579693-ab867900-b83e-11e8-82c9-8df4fb6911a9.png)

I am currently working on the fix for this. `vegas.spec. Spec` singleton seems to be the one that requires changes. I'd like to connect with contributors/founder who wrote that code. My suggestion is to reduce the number of lines in `vegas.spec. Spec` by modularizing it. There are more than 2000 lines in a single file. 
Any feedback?

**Comment by dankolesnikov** [comment]
@aishfenton @oshikiri

**Comment by oshikiri** [comment]
>My suggestion is to reduce the number of lines in vegas.spec. Spec by modularizing it. There are more than 2000 lines in a single file.

`core/src/main/scala/vegas/spec/Spec.scala` is automatically generated by argus package (c.f. https://github.com/vegas-viz/Vegas/issues/93 and [here](https://github.com/vegas-viz/Vegas/blob/master/spec/src/main/scala/vegas/spec/Spec.scala)).

**Comment by dankolesnikov** [comment]
@oshikiri Updates on this:
* It looks that argus needs to be updated to 2.8 (not released yet)
* Assuming there is a breaking change in circe 0.7 - 0.9. Do you know of any?

**Comment by oshikiri** [comment]
>Assuming there is a breaking change in circe 0.7 - 0.9. Do you know of any?

I don't know about it. Could you send a pull request and check using travis-ci?
